version: "3.2"
services:
  web:
    build:
      context: .
      cache_from:
      - rob0h/test-grail-cache
    image: rob0h/test-grail-cache
    external_links:
    - db
  db:
    image: rob0h/test-grail